export const AVATAR: any = {
  doctor1: require("../Avatar/doctor-1.png"),
  doctor2: require("../Avatar/doctor-2.png"),
  doctor3: require("../Avatar/doctor-3.png"),
  doctor4: require("../Avatar/doctor-4.png"),
  doctor5: require("../Avatar/doctor-5.png"),
  doctor6: require("../Avatar/doctor-6.png"),
  doctor7: require("../Avatar/doctor-7.png"),
  avatar1: require("../Avatar/avatar-1.png"),
  avatar2: require("../Avatar/avatar-2.png"),
  avatar3: require("../Avatar/avatar-3.png"),
  avatar4: require("../Avatar/avatar-4.png"),
  avatar5: require("../Avatar/avatar-5.png"),
  avatar6: require("../Avatar/avatar-6.png"),
  avatar7: require("../Avatar/avatar-7.png"),
  avatar8: require("../Avatar/avatar-8.png"),
  avatar9: require("../Avatar/avatar_myra_douglas.png"),
  avatar10: require("../Avatar/avatar_nancy_beck.png"),
  avatar11: require("../Avatar/avatar_11.png"),
  avatar12: require("../Avatar/avatar_12.png"),
  avatar13: require("../Avatar/avatar_13.png"),
  bradley: require("../Avatar/bradley.png"),
  sarah: require("../Avatar/sarah.png"),
  wallace: require("../Avatar/wallace.png"),
  joanna: require("../Avatar/joanna.png"),
};
